name: Release and Deploy

on:
  push:
    branches:
      - master

jobs:
  publish-docker-hub:
    name: Publish image to Docker Hub
    runs-on: ubuntu-latest
    environment: main
    steps:
      - uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/prnt-scavenger:latest
  deploy-to-render:
    name: Deploy image to Render
    needs: publish-docker-hub
    runs-on: ubuntu-latest
    environment: main
    steps:
      - name: Invoke Render deploy hook
        uses: distributhor/workflow-webhook@v3
        with:
          webhook_url: ${{ secrets.RENDER_WEBHOOK_URL }}
